SELECT
--O.ID AS SIPARISID,
--O.DATE_ AS SIPARISTAR�H�,
--I.DATE_ AS FATURATAR�H�,
--DATEPART(YEAR,O.DATE_) AS YIL,
--DATEPART(MONTH,O.DATE_)AS AY,
CT.CITY AS SEHIR,
AVG(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ORTALAMATESLIMATSURESI_SAAT,
MIN(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENKISATESLIMATSURESI_SAAT,
MAX(DATEDIFF(HOUR,O.DATE_,I.DATE_)) AS ENUZUNTESLIMATSURESI_SAAT,
SUM(O.TOTALPRICE) AS TOPLAM_SIPARIS_SAYISI,
COUNT(O.ID) AS SIPARIS_SAYISI
	FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON A.CITYID=CT.ID
	INNER JOIN TOWNS T ON A.TOWNID=T.ID
	INNER JOIN DISTRICTS D ON D.ID =A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID =O.ID
	INNER JOIN INVOICES I ON I.ORDERID =O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
GROUP BY
CT.CITY
--DATEPART(YEAR,O.DATE_) ,
--DATEPART(MONTH,O.DATE_)
--ORDER BY 1,2