SET DATEFIRST 1


SELECT DATENAME(YEAR,GETDATE()),
       DATENAME(MONTH,GETDATE()),
       DATENAME(DAY,GETDATE()),
       DATENAME(HOUR,GETDATE()),
       DATENAME(MINUTE,GETDATE()),
       DATENAME(SECOND,GETDATE()),
       DATENAME(MILLISECOND,GETDATE()),
       DATENAME(DW,GETDATE()),
       DATENAME(WEEK,GETDATE())



