SELECT
DATEPART(MONTH,DATE_) AS AY,
DATEPART(YEAR,DATE_)AS YIL,

CASE WHEN PAYMENTTYPE=1 THEN 'KREDÝ KARTI'
	WHEN PAYMENTTYPE=2 THEN 'BANKA HAVALESÝ'
	END ODEMETURU_ACIKLAMA,
SUM(PAYMENTTOTAL) AS TOPLAMTUTAR

FROM PAYMENTS

GROUP BY DATEPART(MONTH,DATE_),PAYMENTTYPE,DATEPART(YEAR,DATE_)

ORDER BY DATEPART(YEAR,DATE_),DATEPART(MONTH,DATE_)