SELECT U. *,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID DESC) AS SONADDRESS,
(SELECT TOP 1 ADDRESSTEXT FROM ADDRESS WHERE USERID=U.ID ORDER BY ID ASC) AS ILKADDRESS,
(SELECT COUNT( ADDRESSTEXT) FROM ADDRESS WHERE USERID=U.ID) AS ADRESSAYISI

FROM USERS U



