SELECT

 CONVERT(DATE,O.DATE_)AS TARIH,
 SUM(OD.LINETOTAL) AS TOPLAMSATIS_TUTARI,
 SUM(OD.AMOUNT) AS TOPLAMSIPARI_MIKTAR,
 COUNT(OD.ID) AS TOPLAMSIPARISSAYISI
	
	FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON A.CITYID=CT.ID
	INNER JOIN TOWNS T ON A.TOWNID=T.ID
	INNER JOIN DISTRICTS D ON D.ID =A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID =O.ID
	INNER JOIN INVOICES I ON I.ORDERID =O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID


	GROUP BY  CONVERT(DATE,O.DATE_)
	ORDER BY  CONVERT(DATE,O.DATE_)