--ASCII
 --SELECT ASCII('?')  
 --SELECT CHAR('214')
 --SUBSTRING 
--SELECT SUBSTRING('GÜLNÝSA ASLAN',8,12)AS AD
--SELECT * FROM USERS WHERE SUBSTRING(USERNAME_,LEN(USERNAME_),1)='O'
--SELECT CHARINDEX('G','GÜLNÝSA ASLAN',1)

SELECT 'OMER'+'FARUK'+'COLAKOGLU'
SELECT CONCAT('OMER',' ','FARUK',' ','COLAKOGLU')

SELECT CONCAT_WS( ' ','OMER','FARUK','COLAKOGLU')

SELECT *FROM USERS 

SELECT CONCAT_WS(' ',USERNAME_,PASSWORD_,NAMESURNAME) ,*FROM USERS