SELECT 
  --  CT.CITY AS  SEHIRADI,
  ITM.CATEGORY1 ,--ITM.CATEGORY2,ITM.CATEGORY3,
SUM(OD.LINETOTAL) AS   TOPLAMSIPARIS_TUTARI,
SUM(OD.AMOUNT) AS	TOPLAMSIPARIS_ADEDÝ,
COUNT(OD.ID)	AS TOPLAMSIPARIS_SAYISI,
SUM(OD.LINETOTAL)/SUM(OD.AMOUNT) AS ORTALAMABIRIMFIYATI
	
	FROM ORDERS O
	INNER JOIN USERS U ON U.ID=O.USERID
	INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
	INNER JOIN CITIES CT ON A.CITYID=CT.ID
	INNER JOIN TOWNS T ON A.TOWNID=T.ID
	INNER JOIN DISTRICTS D ON D.ID =A.DISTRICTID
	INNER JOIN PAYMENTS P ON P.ORDERID =O.ID
	INNER JOIN INVOICES I ON I.ORDERID =O.ID
	INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
	INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

	WHERE ITM.CATEGORY1='KOZMETIK'

	GROUP BY ITM.CATEGORY1,ITM.CATEGORY2,ITM.CATEGORY3
	ORDER BY COUNT( OD.ID) DESC
	--ORDER BY CT.CITY

